# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LoginSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LoginSample
pod 'Firebase/Auth', '8.6.0'
pod 'Firebase/Firestore', '8.6.0'
pod 'GoogleSignIn', '5.0.2'


end
