# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '16.0'
target 'CLLocationSampleProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CLLocationSampleProject
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'SnapKit'

  target 'CLLocationSampleProjectTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Stubber'
    pod 'Nimble'
    pod 'RxBlocking', '6.5.0'
    pod 'RxTest', '6.5.0'
  end

end
