# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CLLocationSampleProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CLLocationSampleProject
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SnapKit'

  target 'CLLocationSampleProjectTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Stubber'
    pod 'Nimble'
    pod 'RxBlocking'
    pod 'RxTest'
  end

end
